// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20250721140434_AddComments")]
    partial class AddComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.16");

            modelBuilder.Entity("WebApi.Models.Book", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("authors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("average_rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("best_book_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("book_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("books_count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("image_url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("isbn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("isbn13")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("language_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float?>("original_publication_year")
                        .HasColumnType("REAL");

                    b.Property<string>("original_title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ratings_1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ratings_2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ratings_3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ratings_4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ratings_5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ratings_count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("small_image_url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("work_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("work_ratings_count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("work_text_reviews_count")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("WebApi.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
